### ISSUE TITLE
outlets.png does not exist.

### ISSUE THREAD

**Issue by epicgamer6996** [EternityX/DEADCELL-OSHGUI#2]
Outlets.png does not exist, Initializing a form without it will cause a crash.
https://github.com/EternityX/DEADCELL/blob/master/OSHGui/Controls/Form.cpp#L183

**Comment by EternityX** [comment]
By default the form loads it from file for testing purposes, however you can convert the image into a byte array and load it from memory with `Image::FromMemory()` instead.

You can grab the file from my website [here](https://deadcell.cc/media/outlets.png).

If you don't care about the form background, you can simply remove the call to `DrawImage()`.
In fact, the screenshot within the README is shown without the background image.
