### ISSUE TITLE
[Question] Any solutions on updating the controls upon loading saved vars/settings?

### ISSUE THREAD

**Issue by johnj0hn** [EternityX/DEADCELL-OSHGUI#3]
Hello, i've been trying to figure out how to update/reload the controls (checkbox etc) once the form has already been created. Loading the vars before creating the form will set the saved value accordingly to the checkbox, but the values wont be set to the controls after the form has been created and you load them.
I can't wrap my head around this, so i'm here asking for help.

Regards.

**Comment by EternityX** [comment]
Controls are only redrawn/updated when required (changing position, size, etc)
```c
void CheckBox::SetChecked( bool checked ) {
    if( checked_ != checked ) {
        checked_ = checked;
        checkedChangedEvent_.Invoke( this );
        Invalidate(); // tells the renderer to redraw the control.
    }
}
```


Lets say you have a checkbox that is initialized with the variable `epic_bool` from your settings struct, when and if the `epic_bool` is updated, the checkbox will not reflect this change automatically. 

You can manually update the checkbox by calling `SetChecked( epic_bool )` which in return will redraw the checkbox. If you want something more automated you could use `OSHGui::Timer` to call 
the `SetChecked( epic_bool )` function every 250 milliseconds or so.

```c
auto timer = new OSHGui::Timer();
timer->SetInterval( 250 );
timer->Start();
parent->AddControl( timer );

timer->GetTickEvent() += OSHGui::TickEventHandler( [ this, epic_bool ]( Control *sender ) {
    this->SetChecked( epic_bool );
});
```

However this isn't the best approach simply for the fact it's needlessly redrawing the control. Perhaps you can think of something better so you only need to redraw the checkbox when needed.

If you have any further questions, don't hesitate to ask.

**Comment by johnj0hn** [comment]
Hello, I ended up doing what you suggested 
> Manually updating the components

It seems to be quite dirty but oh well, atleast it works.
Thanks for the help.
