### ISSUE TITLE
problem the window movement

### ISSUE THREAD

**Issue by Backq** [EternityX/DEADCELL-OSHGUI#5]
hi, i've been trying to solve this problem the entire day.
my problem is the window moving but the CreateWindow black thing staying at the preset x,y position
however i found a ""solution"" that i don't really like since it adds a white ugly thing by setting createwindow style to WS_OVERLAPPED.
is there anyway i can move the gui without using that? thank you.
(software is based on the desktop and not games)

**Comment by beranos** [comment]
i also need help with this
@EternityX any solutions please?

**Comment by EternityX** [comment]
I've never had this issue but I'll look into it.

**Comment by beranos** [comment]
> I've never had this issue but I'll look into it.

it's not really an issue just an eye challenging thing since default deadcell oshgui / oshgui has this so you can move around the window:
https://imgur.com/a/ToR2lHk
if you replace the window flag from WS_OVERLAPPED to WS_POPUP that thing will go away but as soon you try to move the gui this will happen: (if you move the gui the black thing doesn't follow it)
https://imgur.com/a/MWGhSxh

**Comment by EternityX** [comment]
works fine on my end
https://gyazo.com/ea0db6fa854c25978772442132ced106

you'll need to modify some of the form stuff though, so you can still move the window around as usual.

```c
explicit Window(HINSTANCE inst, const std::string& class_name, const std::string& window_name = "") : m_wnd_class{ 0 } , m_hwnd{ nullptr } {
    m_wnd_class.hInstance = inst;
    m_wnd_class.lpszClassName = class_name.c_str();

    // allocate only one device context for all windows.
    m_wnd_class.style = CS_CLASSDC;

    // ptr to wndproc.
    m_wnd_class.lpfnWndProc = window_proc;

    m_wnd_class.hCursor = LoadCursor(nullptr, IDC_ARROW);

    if (!RegisterClassA(&m_wnd_class))
        return;

    m_hwnd = CreateWindowA(class_name.c_str(), window_name.c_str(), WS_POPUP, 300, 300, 392, 356, GetDesktopWindow(), nullptr, m_wnd_class.hInstance, nullptr);
    if (!m_hwnd)
        return;
}
```

```c
void ui_work(HINSTANCE inst) {
    Window window(inst, Utils::random_string(10));
    Device device(window.m_hwnd);

    // don't call SetWindowLong( window.m_hwnd, GWL_STYLE, WS_POPUP );

    ShowWindow(window.m_hwnd, SW_SHOW);
    UpdateWindow(window.m_hwnd);

    MSG msg;
    ZeroMemory(&msg, sizeof msg);
    if (!IsWindowVisible(window.m_hwnd))
        break;

    if (PeekMessageA(&msg, nullptr, 0, 0, PM_REMOVE)) {
        if (!input.ProcessMessage(&msg)) {
            TranslateMessage(&msg);
            DispatchMessageA(&msg);
        }
    }
    else {
        render(device.m_device);
    }

    std::this_thread::sleep_for(std::chrono::milliseconds(1));
}
```

**Comment by beranos** [comment]
thank you! :)

**Comment by Backq** [comment]
Thank you :P

**Comment by beranos** [comment]
doesn't seem to work :\

**Comment by EternityX** [comment]
You need to call MoveWindow when moving the form.

```c
void Form::CaptionBar::OnMouseMove(const MouseMessage &mouse)
```

something like this (bad way of doing it but you get the point)
```c
if (drag_) {
    POINT p;
    RECT pr;

    GetCursorPos(&p);

    int x = GetParent()->GetLocation().X + (p.x - dragStart_.X);
    int y = GetParent()->GetLocation().Y + (p.y - dragStart_.Y);

    GetWindowRect(GetActiveWindow(), &pr);

    MoveWindow(GetActiveWindow(), x - 6, y - 10, pr.right - pr.left, pr.bottom - pr.top, true);

    GetParent()->SetLocation(GetParent()->GetLocation() + (mouse.GetLocation() - dragStart_));
    dragStart_ = mouse.GetLocation();
}
```

**Comment by beranos** [comment]
thank you worked perfectly!

**Comment by beranos** [comment]
also do you know anything about the cpu usage? since it's at around 30-40 without even touching anything.
@EternityX

**Comment by EternityX** [comment]
you can just sleep for 1ms at the end of your thread

**Comment by beranos** [comment]
thank you!

**Comment by beranos** [comment]
hi @EternityX today i got around making slider float but i got some problems with it:
cpu usage goes + 10 if in the tab im using it theres a sliderfloat
and also it prints random value insteand of 5.5 5.6: example: got the slider on 3.2 but if i print the value it's: 3.18987 but i just want it to be default 3.2
maybe i'm doing something wrong

```	void sliderfloat( std::string text, PointI location, float min, float max, float *value, Control* parent, int default_value ) {
		std::once_flag once_flag;
		std::call_once( once_flag, [&] {
			*value = default_value;
		} );

		TrackBar* track = new TrackBar( );
		track->SetFont( fontBold );
		track->SetPrecision( 1 );
		track->SetLocation( location );
		track->SetText( text );
		track->SetMinimum( min );
		track->SetMaximum( max );

		auto *timer = new OSHGui::Timer( );
		timer->SetInterval( 5 );
		timer->Start( );
		parent->AddControl( timer );
		parent->AddControl( track );
		timer->GetTickEvent( ) += OSHGui::TickEventHandler( [track, value, color]( Control *sender ) {
			track->SetBackColor( Color::FromARGB( color ) );
			track->SetValue( *value );
		} );
		track->GetValueChangedEvent( ) += OSHGui::ValueChangedEventHandler( [track, value]( Control *sender ) {
			*value = track->GetValue( );
		} );
	}
```

**Comment by beranos** [comment]
any reply @EternityX ? sorry for being annoying
